"""``arches-toolkit dev`` — wrap ``docker compose up --watch``.

Baseline compose files and the project Dockerfile ship as CLI package data.
The project directory only needs a project-specific `compose.apps.yaml`
(generated by ``sync-apps``) and/or a `compose.extras.yaml`.
"""

from __future__ import annotations

import os
import shutil
import subprocess
from importlib import resources
from pathlib import Path

import typer

PACKAGE_DATA = "arches_toolkit._data"
BASELINE = ("compose.yaml", "compose.dev.yaml")
PROJECT_OVERLAYS = ("compose.apps.yaml", "compose.extras.yaml")
ARCHES_SRC_OVERLAY = "compose.arches-src.yaml"


def _package_data_path(name: str) -> Path:
    p = Path(str(resources.files(PACKAGE_DATA).joinpath(name)))
    if not p.exists():
        raise typer.BadParameter(f"package data missing: {name}")
    return p


def _compose_argv(
    project_root: Path,
    compose_files: list[Path],
    extra: list[str],
    *,
    build: bool,
) -> list[str]:
    argv = ["docker", "compose", "--project-directory", str(project_root)]
    for f in compose_files:
        argv += ["-f", str(f)]
    argv += ["up", "--watch"]
    if build:
        argv.append("--build")
    argv += list(extra)
    return argv


def dev(
    ctx: typer.Context,
    build: bool = typer.Option(False, "--build", help="Force rebuild before bringing up"),
    project_root: Path = typer.Option(
        Path("."),
        "--project-root",
        help="Project root (default: cwd)",
        show_default=False,
    ),
    dry_run: bool = typer.Option(
        False, "--dry-run", help="Print the docker compose invocation without executing"
    ),
) -> None:
    """Run ``docker compose up --watch`` against the toolkit-shipped baseline."""
    if shutil.which("docker") is None:
        raise typer.BadParameter("docker not found on PATH")

    dockerfile = _package_data_path("Dockerfile")
    compose_files = [_package_data_path(name) for name in BASELINE]

    project_root = project_root.resolve()
    compose_files += [project_root / n for n in PROJECT_OVERLAYS if (project_root / n).exists()]

    if os.environ.get("ARCHES_SRC"):
        compose_files.append(_package_data_path(ARCHES_SRC_OVERLAY))

    argv = _compose_argv(project_root, compose_files, list(ctx.args), build=build)
    env = os.environ.copy()
    env["ARCHES_TOOLKIT_DOCKERFILE"] = str(dockerfile)
    env["ARCHES_TOOLKIT_INIT_SQL"] = str(_package_data_path("init.sql"))

    typer.echo(f"+ ARCHES_TOOLKIT_DOCKERFILE={dockerfile}")
    typer.echo(f"+ {' '.join(argv)}")
    if dry_run:
        return
    completed = subprocess.run(argv, env=env)
    raise typer.Exit(completed.returncode)
