"""``arches-toolkit init <name>`` — scaffold a new Arches project.

Wraps ``arches-admin startproject`` (run inside the toolkit base image so the
host doesn't need a python+arches install) plus the small set of project-side
files the toolkit expects: ``.env``, ``.dockerignore``, settings.py overrides
that read DB/ES/celery host+credentials from the environment.

The generated edits are written *into* the project tree — no toolkit runtime
import. The owner can edit anything afterwards without fighting an import.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import logging
from pathlib import Path
from typing import Optional

import typer

from .._constants import DEFAULT_TOOLKIT_IMAGE, DEFAULT_TOOLKIT_TAG
from .._util import package_data_path as _package_data_path
from .._util import to_python_identifier as _to_python_identifier
from .._util import validate_external_name as _validate_external_name
from .._util import validate_name as _validate_name

# Marker comment so re-running init is idempotent and human-greppable.
SETTINGS_MARKER = "# arches-toolkit:env-overrides"

ENV_TEMPLATE = """\
# Per-environment runtime config. Secrets in real environments come from
# SOPS / k8s secrets, not this file. Local dev only.

PROJECT_IMAGE={name}
PROJECT_TAG=dev
PROJECT_NAME={name}
PROJECT_PACKAGE={package}

ARCHES_TOOLKIT_IMAGE={toolkit_image}
ARCHES_TOOLKIT_TAG={toolkit_tag}

DJANGO_SETTINGS_MODULE={package}.settings
WSGI_APP={package}.wsgi:application
CELERY_APP={package}.celery

PGUSER=postgres
PGPASSWORD=postgres
PGDBNAME={dbname}
"""

SETTINGS_OVERRIDES = """\

{marker}
# Read service hosts and credentials from the environment so the same image
# runs under any compose / k8s environment. Edit freely — these were
# generated by `arches-toolkit init` and are NOT touched by toolkit upgrades.
import os as _os

DATABASES["default"]["HOST"] = _os.environ.get("PGHOST", DATABASES["default"]["HOST"])
DATABASES["default"]["PORT"] = _os.environ.get("PGPORT", DATABASES["default"]["PORT"])
DATABASES["default"]["USER"] = _os.environ.get("PGUSER", DATABASES["default"]["USER"])
DATABASES["default"]["PASSWORD"] = _os.environ.get("PGPASSWORD", DATABASES["default"]["PASSWORD"])
DATABASES["default"]["NAME"] = _os.environ.get("PGDBNAME", DATABASES["default"]["NAME"])

ELASTICSEARCH_HOSTS[0]["scheme"] = _os.environ.get("ESSCHEME", ELASTICSEARCH_HOSTS[0]["scheme"])
ELASTICSEARCH_HOSTS[0]["host"] = _os.environ.get("ESHOST", ELASTICSEARCH_HOSTS[0]["host"])
ELASTICSEARCH_HOSTS[0]["port"] = int(_os.environ.get("ESPORT", ELASTICSEARCH_HOSTS[0]["port"]))

CELERY_BROKER_URL = _os.environ.get("RABBITMQ_URL", CELERY_BROKER_URL)
"""

GITIGNORE_LINES = [
    ".env",
    ".env.local",
    "node_modules/",
    "frontend_configuration/",
    "uploadedfiles/",
    "static_root/",
    "logs/",
    "*.log",
    "__pycache__/",
    "*.py[cod]",
    ".venv/",
    "venv/",
    ".pytest_cache/",
]


def _validate_image_repo(image: str) -> str:
    """Reject a tag embedded in the image flag — the tag has its own flag.

    A colon in the last path segment is a tag; a colon in an earlier segment
    is a registry port (``localhost:5000/img``) and is fine. Without this,
    image+tag joining produces a double-colon reference and docker fails
    with an opaque "invalid reference format".
    """
    if ":" in image.rsplit("/", 1)[-1]:
        repo, _, tag = image.rpartition(":")
        raise typer.BadParameter(
            f"--arches-toolkit-image must not include a tag — got {image!r}.\n"
            f"Use: --arches-toolkit-image {repo} --arches-toolkit-tag {tag}"
        )
    return image


def _run_arches_admin(parent: Path, name: str, package: str, image: str) -> None:
    uid_gid = f"{os.getuid()}:{os.getgid()}"
    # Django's startproject takes <name> (must be a Python identifier) and
    # an optional --directory (any path; must exist). Pass `package` as the
    # name and the kebab-or-snake `name` as the directory so kebab-case
    # project dirs are supported. Pre-create the dir — Django requires it.
    # --entrypoint: never inherit the image's ENTRYPOINT — a foreign image
    # (e.g. one with a relative entrypoint path) would otherwise hijack the
    # invocation and fail before our command runs.
    cmd = [
        "docker", "run", "--rm",
        "-v", f"{parent}:/work",
        "-u", "0",
        "-w", "/work",
        "--entrypoint", "sh",
        image,
        "-c",
        f"printf '#!/bin/sh\\n' > /usr/local/bin/npm && chmod +x /usr/local/bin/npm && "
        f"mkdir -p /work/{name} && "
        f"arches-admin startproject {package} --directory {name} && "
        f"chown -R {uid_gid} /work/{name}",

    ]
    logging.getLogger(__name__).info(f"+ {' '.join(cmd)}")
    r = subprocess.run(cmd)
    if r.returncode != 0:
        raise typer.Exit(r.returncode)


def _probe_arches_version(image: str) -> str | None:
    """Ask the base image which arches dist it ships. None on any failure."""
    cmd = [
        "docker", "run", "--rm", "--entrypoint", "python", image, "-c",
        "from importlib.metadata import version; print(version('arches'))",
    ]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0 or not r.stdout.strip():
        return None
    return r.stdout.strip().splitlines()[-1].strip() or None


def _pin_arches_dependency(pyproject_path: Path, version: str) -> str:
    """Rewrite the template's arches bound to ``arches==<base version>``.

    arches-admin's template writes the anticipated-final range (e.g.
    ``arches>=8.2.0,<8.3.0``), which no pre-release can satisfy (PEP 440:
    8.2.0a4 < 8.2.0) — unbuildable until the final release. The base image
    is authoritative for the arches version anyway, so pin to what it
    actually ships.
    """
    import tomlkit

    if not pyproject_path.exists():
        return "pyproject.toml: not found — skipped arches pin"
    doc = tomlkit.parse(pyproject_path.read_text(encoding="utf-8"))
    project = doc.get("project")
    deps = project.get("dependencies") if project is not None else None
    if deps is None:
        return "pyproject.toml: no [project.dependencies] — skipped arches pin"
    pinned = f"arches=={version}"
    for i, spec in enumerate(deps):
        s = str(spec).strip()
        dep_name = s
        for sep in ("[", "==", "!=", ">=", "<=", "~=", ">", "<", " ", ";", "@"):
            j = dep_name.find(sep)
            if j != -1:
                dep_name = dep_name[:j]
        if dep_name.strip().lower() != "arches":
            continue
        if s == pinned:
            return f"pyproject.toml: arches already pinned to {version}"
        deps[i] = pinned
        pyproject_path.write_text(tomlkit.dumps(doc), encoding="utf-8")
        return f"pyproject.toml: arches pinned to base image version ({s!r} → {pinned!r})"
    return "pyproject.toml: no arches dependency found — skipped arches pin"


def _patch_settings(settings_path: Path) -> str:
    text = settings_path.read_text(encoding="utf-8")
    if SETTINGS_MARKER in text:
        return "settings.py: env-overrides already present (skipped)"
    overrides = SETTINGS_OVERRIDES.format(marker=SETTINGS_MARKER)
    settings_path.write_text(text.rstrip() + "\n" + overrides, encoding="utf-8")
    return "settings.py: appended env-overrides block"


def _write_env(target: Path, **values: str) -> str:
    env_path = target / ".env"
    if env_path.exists():
        return ".env: already exists (left untouched)"
    env_path.write_text(ENV_TEMPLATE.format(**values), encoding="utf-8")
    return ".env: written"


def _write_dockerignore(target: Path) -> str:
    dst = target / ".dockerignore"
    src = _package_data_path(".dockerignore")
    if dst.exists():
        return ".dockerignore: already exists (left untouched)"
    shutil.copyfile(src, dst)
    return ".dockerignore: written"


def _ensure_gitignore(target: Path) -> str:
    gitignore = target / ".gitignore"
    existing = gitignore.read_text(encoding="utf-8") if gitignore.exists() else ""
    existing_lines = {line.strip() for line in existing.splitlines() if line.strip()}
    additions = [line for line in GITIGNORE_LINES if line not in existing_lines]
    if not additions:
        return ".gitignore: no changes"
    block = "\n# arches-toolkit init\n" + "\n".join(additions) + "\n"
    if existing and not existing.endswith("\n"):
        existing += "\n"
    gitignore.write_text(existing + block, encoding="utf-8")
    return f".gitignore: appended {len(additions)} entries"


def init(
    name: str = typer.Argument(..., help="Project name (lowercase; kebab-case or snake_case)"),
    target_dir: Optional[Path] = typer.Option(
        None, "--target-dir", "-d",
        help="Where to create the project (default: ./<name>)",
    ),
    arches_toolkit_image: str = typer.Option(
        DEFAULT_TOOLKIT_IMAGE, "--arches-toolkit-image",
        help="Base image to run arches-admin from + reference in .env",
    ),
    arches_toolkit_tag: str = typer.Option(
        DEFAULT_TOOLKIT_TAG, "--arches-toolkit-tag",
        help="Tag of the toolkit image (paired with --arches-toolkit-image)",
    ),
    package: Optional[str] = typer.Option(
        None, "--package", help="Python package name (defaults to project name)",
    ),
    force: bool = typer.Option(
        False, "--force", help="Re-run inside an existing project dir",
    ),
) -> None:
    """Scaffold a new Arches project ready for ``arches-toolkit dev``."""
    if shutil.which("docker") is None:
        raise typer.BadParameter("docker not found on PATH")
    # name can be kebab- or snake-case (used as dir/distribution name);
    # package must be a Python identifier (snake_case). Default-derive by
    # converting hyphens to underscores.
    name = _validate_external_name(name, what="project name")
    package = _validate_name(package or _to_python_identifier(name), what="package")
    _validate_image_repo(arches_toolkit_image)

    target = (target_dir or Path.cwd() / name).resolve()
    parent = target.parent
    parent.mkdir(parents=True, exist_ok=True)

    if target.exists() and not force:
        raise typer.BadParameter(
            f"{target}: already exists — pass --force to re-run init inside it"
        )

    image_ref = f"{arches_toolkit_image}:{arches_toolkit_tag}"
    if not target.exists():
        _run_arches_admin(parent, target.name, package, image_ref)
    else:
        typer.echo(f"reusing existing dir {target}")

    settings_path = target / package / "settings.py"
    if not settings_path.exists():
        raise typer.BadParameter(
            f"{settings_path}: not found — arches-admin scaffold did not produce expected layout"
        )

    typer.echo("")
    arches_version = _probe_arches_version(image_ref)
    if arches_version:
        typer.echo(_pin_arches_dependency(target / "pyproject.toml", arches_version))
    else:
        typer.echo(
            "warning: could not read the arches version from the base image — "
            "pyproject.toml arches bound left at the template default"
        )
    typer.echo(_patch_settings(settings_path))
    typer.echo(
        _write_env(
            target,
            name=name,
            package=package,
            dbname=name.replace("-", "_"),
            toolkit_image=arches_toolkit_image,
            toolkit_tag=arches_toolkit_tag,
        )
    )
    typer.echo(_write_dockerignore(target))
    typer.echo(_ensure_gitignore(target))

    typer.echo("")
    typer.echo("Next:")
    typer.echo(f"  cd {target.relative_to(Path.cwd()) if target.is_relative_to(Path.cwd()) else target}")
    typer.echo("  arches-toolkit dev --build")
