"""``arches-toolkit init <name>`` — scaffold a new Arches project.

Wraps ``arches-admin startproject`` (run inside the toolkit base image so the
host doesn't need a python+arches install) plus the small set of project-side
files the toolkit expects: ``.env``, ``.dockerignore``, settings.py overrides
that read DB/ES/celery host+credentials from the environment.

The generated edits are written *into* the project tree — no toolkit runtime
import. The owner can edit anything afterwards without fighting an import.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
from importlib import resources
from pathlib import Path
from typing import Optional

import typer

PACKAGE_DATA = "arches_toolkit._data"

# Marker comment so re-running init is idempotent and human-greppable.
SETTINGS_MARKER = "# arches-toolkit:env-overrides"

ENV_TEMPLATE = """\
# Per-environment runtime config. Secrets in real environments come from
# SOPS / k8s secrets, not this file. Local dev only.

PROJECT_IMAGE={name}
PROJECT_TAG=dev
PROJECT_NAME={name}
PROJECT_PACKAGE={package}

ARCHES_TOOLKIT_IMAGE={toolkit_image}
ARCHES_TOOLKIT_TAG={toolkit_tag}

DJANGO_SETTINGS_MODULE={package}.settings
WSGI_APP={package}.wsgi:application
CELERY_APP={package}.celery

PGUSER=postgres
PGPASSWORD=postgres
PGDBNAME={name}
"""

SETTINGS_OVERRIDES = """\

{marker}
# Read service hosts and credentials from the environment so the same image
# runs under any compose / k8s environment. Edit freely — these were
# generated by `arches-toolkit init` and are NOT touched by toolkit upgrades.
import os as _os

DATABASES["default"]["HOST"] = _os.environ.get("PGHOST", DATABASES["default"]["HOST"])
DATABASES["default"]["PORT"] = _os.environ.get("PGPORT", DATABASES["default"]["PORT"])
DATABASES["default"]["USER"] = _os.environ.get("PGUSER", DATABASES["default"]["USER"])
DATABASES["default"]["PASSWORD"] = _os.environ.get("PGPASSWORD", DATABASES["default"]["PASSWORD"])
DATABASES["default"]["NAME"] = _os.environ.get("PGDBNAME", DATABASES["default"]["NAME"])

ELASTICSEARCH_HOSTS = [{{
    "scheme": _os.environ.get("ESSCHEME", "http"),
    "host": _os.environ.get("ESHOST", "localhost"),
    "port": int(_os.environ.get("ESPORT", "9200")),
}}]
ELASTICSEARCH_CONNECTION_OPTIONS = {{"request_timeout": 30, "verify_certs": False}}

CELERY_BROKER_URL = _os.environ.get("RABBITMQ_URL", CELERY_BROKER_URL or "")
"""

GITIGNORE_LINES = [
    ".env",
    ".env.local",
    "node_modules/",
    "frontend_configuration/",
    "uploadedfiles/",
    "static_root/",
    "logs/",
    "*.log",
    "__pycache__/",
    "*.py[cod]",
    ".venv/",
    "venv/",
    ".pytest_cache/",
]


def _validate_name(name: str) -> str:
    if not re.fullmatch(r"[a-z][a-z0-9_]*", name):
        raise typer.BadParameter(
            f"project name {name!r} must start with a lowercase letter and contain "
            "only lowercase letters, digits, and underscores"
        )
    return name


def _package_data_path(name: str) -> Path:
    p = Path(str(resources.files(PACKAGE_DATA).joinpath(name)))
    if not p.exists():
        raise typer.BadParameter(f"package data missing: {name}")
    return p


def _run_arches_admin(parent: Path, name: str, image: str) -> None:
    uid_gid = f"{os.getuid()}:{os.getgid()}"
    cmd = [
        "docker", "run", "--rm",
        "-v", f"{parent}:/work",
        "-u", "0",
        "-w", "/work",
        image,
        "sh", "-c",
        f"arches-admin startproject {name}; chown -R {uid_gid} /work/{name}",
    ]
    typer.echo(f"+ {' '.join(cmd)}")
    r = subprocess.run(cmd)
    if r.returncode != 0:
        raise typer.Exit(r.returncode)


def _patch_settings(settings_path: Path) -> str:
    text = settings_path.read_text(encoding="utf-8")
    if SETTINGS_MARKER in text:
        return "settings.py: env-overrides already present (skipped)"
    overrides = SETTINGS_OVERRIDES.format(marker=SETTINGS_MARKER)
    settings_path.write_text(text.rstrip() + "\n" + overrides, encoding="utf-8")
    return f"settings.py: appended env-overrides block"


def _write_env(target: Path, **values: str) -> str:
    env_path = target / ".env"
    if env_path.exists():
        return ".env: already exists (left untouched)"
    env_path.write_text(ENV_TEMPLATE.format(**values), encoding="utf-8")
    return ".env: written"


def _write_dockerignore(target: Path) -> str:
    dst = target / ".dockerignore"
    src = _package_data_path(".dockerignore")
    if dst.exists():
        return ".dockerignore: already exists (left untouched)"
    shutil.copyfile(src, dst)
    return ".dockerignore: written"


def _ensure_gitignore(target: Path) -> str:
    gitignore = target / ".gitignore"
    existing = gitignore.read_text(encoding="utf-8") if gitignore.exists() else ""
    existing_lines = {line.strip() for line in existing.splitlines() if line.strip()}
    additions = [line for line in GITIGNORE_LINES if line not in existing_lines]
    if not additions:
        return ".gitignore: no changes"
    block = "\n# arches-toolkit init\n" + "\n".join(additions) + "\n"
    if existing and not existing.endswith("\n"):
        existing += "\n"
    gitignore.write_text(existing + block, encoding="utf-8")
    return f".gitignore: appended {len(additions)} entries"


def init(
    name: str = typer.Argument(..., help="Project name (lowercase, valid Python identifier)"),
    target_dir: Optional[Path] = typer.Option(
        None, "--target-dir", "-d",
        help="Where to create the project (default: ./<name>)",
    ),
    arches_toolkit_image: str = typer.Option(
        "arches-toolkit-local-test", "--arches-toolkit-image",
        help="Base image to run arches-admin from + reference in .env",
    ),
    arches_toolkit_tag: str = typer.Option(
        "latest", "--arches-toolkit-tag",
        help="Tag of the toolkit image (paired with --arches-toolkit-image)",
    ),
    package: Optional[str] = typer.Option(
        None, "--package", help="Python package name (defaults to project name)",
    ),
    force: bool = typer.Option(
        False, "--force", help="Re-run inside an existing project dir",
    ),
) -> None:
    """Scaffold a new Arches project ready for ``arches-toolkit dev``."""
    if shutil.which("docker") is None:
        raise typer.BadParameter("docker not found on PATH")
    name = _validate_name(name)
    package = _validate_name(package or name)

    target = (target_dir or Path.cwd() / name).resolve()
    parent = target.parent
    parent.mkdir(parents=True, exist_ok=True)

    if target.exists() and not force:
        raise typer.BadParameter(
            f"{target}: already exists — pass --force to re-run init inside it"
        )

    image_ref = f"{arches_toolkit_image}:{arches_toolkit_tag}"
    if not target.exists():
        _run_arches_admin(parent, target.name, image_ref)
    else:
        typer.echo(f"reusing existing dir {target}")

    settings_path = target / package / "settings.py"
    if not settings_path.exists():
        raise typer.BadParameter(
            f"{settings_path}: not found — arches-admin scaffold did not produce expected layout"
        )

    typer.echo("")
    typer.echo(_patch_settings(settings_path))
    typer.echo(
        _write_env(
            target,
            name=name,
            package=package,
            toolkit_image=arches_toolkit_image,
            toolkit_tag=arches_toolkit_tag,
        )
    )
    typer.echo(_write_dockerignore(target))
    typer.echo(_ensure_gitignore(target))

    typer.echo("")
    typer.echo("Next:")
    typer.echo(f"  cd {target.relative_to(Path.cwd()) if target.is_relative_to(Path.cwd()) else target}")
    typer.echo("  arches-toolkit dev --build")
