"""``arches-toolkit sync-apps`` — project pyproject.toml + compose.apps.yaml.

Reads ``apps.yaml`` and:

* For each ``mode: release`` entry, ensures the package is listed in the
  project's ``[project.dependencies]``. Managed entries are tracked under
  ``[tool.arches-toolkit] managed_apps = [...]`` so that release entries
  removed from ``apps.yaml`` are also removed from the dependency list.
  Entries the user added by hand (i.e. not in ``managed_apps``) are left
  alone.

* For each ``mode: develop`` entry, regenerates ``compose.apps.yaml`` with a
  service fragment that bind-mounts a sibling clone of the app and installs
  it editable into the venv on the next ``uv sync``.
"""

from __future__ import annotations

from pathlib import Path

import tomlkit
import typer
import yaml
from tomlkit.items import Array, Table

from .. import apps_manifest as manifest_mod
from ..apps_manifest import AppEntry, AppsManifest

PYPROJECT_FILENAME = "pyproject.toml"
COMPOSE_APPS_FILENAME = "compose.apps.yaml"
GENERATED_HEADER = (
    "# Generated by arches-toolkit sync-apps. Do not edit by hand —\n"
    "# changes will be overwritten on the next run.\n"
    "# Source of truth: apps.yaml\n"
)


def _release_dep_spec(entry: AppEntry) -> str:
    """Render a PEP 508 dependency string for a release-mode entry."""
    if entry.source == "git":
        # Git deps in pyproject.toml dependencies require a marker form;
        # tomlkit will write it, but uv needs ``[tool.uv.sources]`` for full
        # support. We emit the bare package and let the user wire the source.
        return entry.package
    if entry.version:
        spec = entry.version.strip()
        if spec[:1] in {"=", ">", "<", "~", "!", "^"}:
            return f"{entry.package}{spec}"
        # Bare version → treat as exact pin via ==.
        return f"{entry.package}=={spec}"
    return entry.package


def _ensure_table(parent, key: str) -> Table:
    if key not in parent:
        parent[key] = tomlkit.table()
    return parent[key]


def _read_managed(doc) -> list[str]:
    tool = doc.get("tool")
    if tool is None:
        return []
    section = tool.get("arches-toolkit")
    if section is None:
        return []
    arr = section.get("managed_apps")
    if arr is None:
        return []
    return [str(x) for x in arr]


def _write_managed(doc, names: list[str]) -> None:
    tool = _ensure_table(doc, "tool")
    section = _ensure_table(tool, "arches-toolkit")
    arr = tomlkit.array()
    for n in sorted(set(names)):
        arr.append(n)
    arr.multiline(True)
    section["managed_apps"] = arr


def _project_deps_array(doc) -> Array:
    project = doc.get("project")
    if project is None:
        raise typer.BadParameter(
            f"{PYPROJECT_FILENAME}: missing [project] table — is this a PEP 621 project?"
        )
    if "dependencies" not in project:
        project["dependencies"] = tomlkit.array().multiline(True)
    deps = project["dependencies"]
    if not isinstance(deps, Array):
        # tomlkit returns an Array proxy; coerce just in case.
        new = tomlkit.array()
        for item in deps:
            new.append(item)
        new.multiline(True)
        project["dependencies"] = new
        deps = project["dependencies"]
    return deps


def _dep_package_name(spec: str) -> str:
    """Extract the bare package name from a PEP 508 dependency string."""
    s = spec.strip()
    for sep in ("[", "==", "!=", ">=", "<=", "~=", ">", "<", " ", ";", "@"):
        i = s.find(sep)
        if i != -1:
            s = s[:i]
    return s.strip()


def _sync_pyproject(release_apps: list[AppEntry], project_root: Path) -> str:
    """Update pyproject.toml in place. Returns a status string for logging."""
    pyproject_path = project_root / PYPROJECT_FILENAME
    if not pyproject_path.exists():
        raise typer.BadParameter(
            f"{pyproject_path}: not found — sync-apps must run at the project root"
        )
    original_text = pyproject_path.read_text(encoding="utf-8")
    doc = tomlkit.parse(original_text)

    deps = _project_deps_array(doc)
    previously_managed = set(_read_managed(doc))
    desired_specs = {entry.package: _release_dep_spec(entry) for entry in release_apps}
    desired_names = set(desired_specs)

    # Build a fresh list, preserving non-managed items in original order.
    kept: list[str] = []
    seen_managed: set[str] = set()
    for spec in list(deps):
        spec_str = str(spec).strip()
        name = _dep_package_name(spec_str)
        if name in previously_managed:
            # Drop — we'll re-add the desired form below.
            seen_managed.add(name)
            continue
        if name in desired_names:
            # User had already added this by hand; replace with the managed
            # form to keep version specs consistent.
            seen_managed.add(name)
            continue
        kept.append(spec_str)

    # Append desired specs deterministically (sorted by package name).
    for name in sorted(desired_names):
        kept.append(desired_specs[name])

    # Rebuild the array preserving multiline formatting.
    new_deps = tomlkit.array()
    for spec in kept:
        new_deps.append(spec)
    if kept:
        new_deps.multiline(True)
    doc["project"]["dependencies"] = new_deps

    _write_managed(doc, sorted(desired_names))

    new_text = tomlkit.dumps(doc)
    if new_text == original_text:
        return "pyproject.toml: no changes"
    pyproject_path.write_text(new_text, encoding="utf-8")
    return "pyproject.toml: updated"


def _develop_repo_dirname(entry: AppEntry) -> str:
    """Best-effort directory name for a develop-mode clone."""
    if entry.repo:
        last = entry.repo.rstrip("/").rsplit("/", 1)[-1]
        if last.endswith(".git"):
            last = last[:-4]
        if last:
            return last
    return entry.package


def _build_compose_apps(develop_apps: list[AppEntry]) -> dict:
    """Build the compose.apps.yaml document for develop-mode apps."""
    services: dict[str, dict] = {}
    for entry in develop_apps:
        dirname = _develop_repo_dirname(entry)
        host_path = f"../{dirname}"
        container_path = f"/opt/apps/{dirname}"
        # Fragment merged with the main `web` service via compose's deep merge.
        # Bind mount + an editable install hint for the dev workflow.
        services.setdefault("web", {"volumes": []})
        services["web"]["volumes"].append(f"{host_path}:{container_path}")
        services.setdefault("worker", {"volumes": []})
        services["worker"]["volumes"].append(f"{host_path}:{container_path}")
    doc: dict = {"services": services}
    return doc


def _sync_compose_apps(develop_apps: list[AppEntry], project_root: Path) -> str:
    compose_path = project_root / COMPOSE_APPS_FILENAME
    if not develop_apps:
        if compose_path.exists():
            compose_path.unlink()
            return f"{COMPOSE_APPS_FILENAME}: removed (no develop-mode apps)"
        return f"{COMPOSE_APPS_FILENAME}: skipped (no develop-mode apps)"
    doc = _build_compose_apps(develop_apps)
    body = yaml.safe_dump(doc, sort_keys=False, default_flow_style=False)
    text = GENERATED_HEADER + body
    if compose_path.exists() and compose_path.read_text(encoding="utf-8") == text:
        return f"{COMPOSE_APPS_FILENAME}: no changes"
    compose_path.write_text(text, encoding="utf-8")
    return f"{COMPOSE_APPS_FILENAME}: updated"


def sync_apps(
    manifest_path: Path = typer.Option(
        Path("apps.yaml"),
        "--manifest",
        help="Path to apps.yaml (default: ./apps.yaml)",
        show_default=False,
    ),
    project_root: Path = typer.Option(
        Path("."),
        "--project-root",
        help="Project root containing pyproject.toml (default: cwd)",
        show_default=False,
    ),
) -> None:
    if not manifest_path.exists():
        raise typer.BadParameter(
            f"{manifest_path}: not found — run `arches-toolkit add-app` first"
        )
    manifest: AppsManifest = manifest_mod.load(manifest_path)
    release = list(manifest_mod.iter_release(manifest))
    develop = list(manifest_mod.iter_develop(manifest))
    typer.echo(_sync_pyproject(release, project_root))
    typer.echo(_sync_compose_apps(develop, project_root))


# Re-exported for tests.
__all__ = [
    "sync_apps",
    "_sync_pyproject",
    "_sync_compose_apps",
    "_release_dep_spec",
    "_build_compose_apps",
]
