apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arches.fullname" . }}-http
  labels:
    tier: backend
    {{- include "arches.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      tier: backend
      {{- include "arches.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        tier: backend
        {{- include "arches.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/configmap-env: {{ include (print $.Template.BasePath "/configmap-env.yaml") . | sha256sum }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "arches.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: {{ .Chart.Name }}-init
          envFrom:
          - configMapRef:
              name: {{ template "arches.fullname" . }}-env
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sh
            - -euxc
            - |
              python manage.py migrate --noinput
              python manage.py createcachetable
              python manage.py collectstatic --noinput
          env:
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                key: {{ default .Values.postgresqlPasswordKey "postgres-password" }}
                name: {{ printf "%s-postgresql" .Release.Name }}
          - name: CELERY_BROKER_URL
            valueFrom:
              secretKeyRef:
                key: celery-broker-url
                name: {{ template "arches.fullname" $ }}
          - name: RABBITMQ_URL
            valueFrom:
              secretKeyRef:
                key: celery-broker-url
                name: {{ template "arches.fullname" $ }}
          volumeMounts:
          - name: frontend-configuration
            mountPath: /var/arches/frontend_configuration
          - name: uploadedfiles
            mountPath: /var/arches/uploadedfiles
      containers:
        - name: {{ .Chart.Name }}
          envFrom:
          - configMapRef:
              name: {{ template "arches.fullname" . }}-env
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sh
            - -euxc
            - exec gunicorn --bind 0.0.0.0:8000 --workers {{ .Values.gunicornWorkers | default 1 }} "${WSGI_APP}"
          volumeMounts:
          - name: frontend-configuration
            mountPath: /var/arches/frontend_configuration
            readOnly: true
          - name: uploadedfiles
            mountPath: /var/arches/uploadedfiles
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                key: {{ default .Values.postgresqlPasswordKey "postgres-password" }}
                name: {{ printf "%s-postgresql" .Release.Name }}
          - name: COUCHDB_PASS
            value: UNSET
            #alueFrom:
            # secretKeyRef:
            #   key: adminPassword
            #   name: {{ printf "%s-couchdb" .Release.Name }}
          - name: CELERY_BROKER_URL
            valueFrom:
              secretKeyRef:
                key: celery-broker-url
                name: {{ template "arches.fullname" $ }}
          - name: RABBITMQ_URL
            valueFrom:
              secretKeyRef:
                key: celery-broker-url
                name: {{ template "arches.fullname" $ }}
          {{- range $env, $value := .Values.secretEnv }}
          - name: {{ $env }}
            valueFrom:
              secretKeyRef:
                key: {{ $env }}
                name: {{ template "arches.fullname" $ }}-env
          {{- end }}
      volumes:
      - name: frontend-configuration
        emptyDir: {}
      - name: uploadedfiles
      {{- if .Values.persistence.uploadedfiles.enabled }}
        persistentVolumeClaim:
          claimName: {{ default (printf "%s-uploadedfiles" (include "arches.fullname" .)) .Values.persistence.uploadedfiles.existingClaim }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
