apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "devservices.fullname" . }}-elasticsearch
  labels:
    {{- include "devservices.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  {{- with .Values.elasticsearch.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.elasticsearch.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devservices.fullname" . }}-elasticsearch
  labels:
    {{- include "devservices.labels" . | nindent 4 }}
    app.kubernetes.io/component: elasticsearch
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: elasticsearch
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: {{ .Values.elasticsearch.image }}
          env:
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "false"
            - name: ingest.geoip.downloader.enabled
              value: "false"
            - name: cluster.routing.allocation.disk.threshold_enabled
              value: "false"
            - name: ES_JAVA_OPTS
              value: {{ .Values.elasticsearch.javaOpts | quote }}
          ports:
            - name: http
              containerPort: 9200
          readinessProbe:
            httpGet:
              path: /_cluster/health
              port: http
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            tcpSocket:
              port: http
            periodSeconds: 30
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
          resources:
            {{- toYaml .Values.elasticsearch.resources | nindent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "devservices.fullname" . }}-elasticsearch
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "devservices.fullname" . }}-elasticsearch
  labels:
    {{- include "devservices.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 9200
      targetPort: http
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: elasticsearch
