apiVersion: v1
kind: Service
metadata:
  name: {{ include "arches.fullname" . }}-web
  labels:
    {{- include "arches.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.web.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "arches.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
{{- if .Values.api.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "arches.fullname" . }}-api
  labels:
    {{- include "arches.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "arches.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
{{- end }}
{{- if .Values.static.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "arches.fullname" . }}-static
  labels:
    {{- include "arches.labels" . | nindent 4 }}
    app.kubernetes.io/component: static
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.static.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "arches.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: static
{{- end }}
{{- if .Values.cantaloupe.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "arches.fullname" . }}-cantaloupe
  labels:
    {{- include "arches.labels" . | nindent 4 }}
    app.kubernetes.io/component: cantaloupe
spec:
  type: ClusterIP
  ports:
    - port: 8182
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "arches.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: cantaloupe
{{- end }}
